### ISSUE TITLE
Improve logging/notification of translation script failures

### ISSUE THREAD

**Issue by amangano-edx** [edx/ecommerce-scripts#63]
Right now, the translation script logs everything at info level, and Jenkins builds pass even if the script failed to merge the PR it generated. This can make it difficult to monitor the health of these jobs in Jenkins.

**Comment by amangano-edx** [comment]
Also, for certain types of failures (like compilemessages failures), we do not log anything. Instead, we leave a comment on the PR. This could make it difficult to figure out why a particular job failed, if, for instance, Github is down and we are unable to leave the PR comment there.

**Comment by Ayub-Khan** [comment]
@amangano-edx  can we close this, as we started failing builds in https://github.com/edx/ecommerce-scripts/pull/85.
