### ISSUE TITLE
More robust translation script environment setup

### ISSUE THREAD

**Issue by amangano-edx** [edx/ecommerce-scripts#64]
The translation scripts are very brittle in that they require the workspace and remote repository to be completely clean prior to running them. There must not be a local copy of the repo already in the workspace, or else the script will fail during the clone step. There must not already be a branch with the same name as the branch the script will create (for transifex/pull.py, it's the 'update-translations' branch), or else the script may fail to push changes to the remote and open a PR. These nuances can lead to problems when the script is not able to fully cleanup after itself, such as when the PR created by the script could not be merged due to pending status checks. It would be great if we could do some refactoring to handle cases like these and create a more robust script.

**Comment by Ayub-Khan** [comment]
Done.
