### ISSUE TITLE
Improve error handling when attempting to merge translations PRs

### ISSUE THREAD

**Issue by amangano-edx** [edx/ecommerce-scripts#65]
The Repo.merge_pr method (transifex/utils.py) currently assumes that if a merge attempt fails, it must have been because either the Travis status checks failed or the status checks are pending. In reality, there could be lots of other reasons why the merge failed (merge method not allowed, Github is down, etc). It would be great if we could detect these other types of failures and handle them appropriately.

**Comment by Ayub-Khan** [comment]
Already done.
